/* eslint-disable */
export default {
  queryCost: 1,
  latitude: 52.2356,
  longitude: 21.0104,
  resolvedAddress: 'Warszawa, Woj. Mazowieckie, Polska',
  address: 'warszawa',
  timezone: 'Europe/Warsaw',
  tzoffset: 2,
  days: [
    {
      datetime: '2022-09-21',
      datetimeEpoch: 1663711200,
      tempmax: 14.7,
      tempmin: 9,
      temp: 11.3,
      feelslikemax: 14.7,
      feelslikemin: 6.7,
      feelslike: 10.4,
      dew: 8.5,
      humidity: 84,
      precip: 1.5,
      precipprob: 33.3,
      precipcover: 8.33,
      preciptype: ['rain'],
      snow: 0,
      snowdepth: 0,
      windgust: 35.6,
      windspeed: 16.5,
      winddir: 315.9,
      pressure: 1019.5,
      cloudcover: 88.8,
      visibility: 19.3,
      solarradiation: 146.5,
      solarenergy: 12.9,
      uvindex: 5,
      severerisk: 10,
      sunrise: '06:19:56',
      sunriseEpoch: 1663733996,
      sunset: '18:37:16',
      sunsetEpoch: 1663778236,
      moonphase: 0.91,
      conditions: 'Partially cloudy',
      description: 'Partly cloudy throughout the day.',
      icon: 'partly-cloudy-day',
      stations: ['EPWA', 'E1334', 'remote', 'EPMO'],
      source: 'comb',
      hours: [
        {
          datetime: '00:00:00',
          datetimeEpoch: 1663711200,
          temp: 9,
          feelslike: 6.9,
          humidity: 93.14,
          dew: 7.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 20.5,
          windspeed: 13,
          winddir: 290,
          pressure: 1017,
          visibility: 10,
          cloudcover: 85.4,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['EPWA', 'EPMO'],
          source: 'obs',
        },
        {
          datetime: '01:00:00',
          datetimeEpoch: 1663714800,
          temp: 9,
          feelslike: 6.7,
          humidity: 93.14,
          dew: 7.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 21.2,
          windspeed: 14.8,
          winddir: 309,
          pressure: 1017,
          visibility: 10,
          cloudcover: 90.4,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['EPWA', 'EPMO'],
          source: 'obs',
        },
        {
          datetime: '02:00:00',
          datetimeEpoch: 1663718400,
          temp: 9,
          feelslike: 7.1,
          humidity: 93.45,
          dew: 8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 19.8,
          windspeed: 11.4,
          winddir: 290,
          pressure: 1017,
          visibility: 10,
          cloudcover: 26.2,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['EPWA', 'EPMO'],
          source: 'obs',
        },
        {
          datetime: '03:00:00',
          datetimeEpoch: 1663722000,
          temp: 9,
          feelslike: 6.9,
          humidity: 99.67,
          dew: 8.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 20.2,
          windspeed: 13,
          winddir: 290,
          pressure: 1017,
          visibility: 10,
          cloudcover: 88,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['EPWA', 'EPMO'],
          source: 'obs',
        },
        {
          datetime: '04:00:00',
          datetimeEpoch: 1663725600,
          temp: 9.9,
          feelslike: 7.8,
          humidity: 93.5,
          dew: 8.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 21.6,
          windspeed: 14.8,
          winddir: 300,
          pressure: 1018,
          visibility: 9.9,
          cloudcover: 88.6,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['EPWA', 'EPMO'],
          source: 'obs',
        },
        {
          datetime: '05:00:00',
          datetimeEpoch: 1663729200,
          temp: 10,
          feelslike: 7.7,
          humidity: 93.19,
          dew: 8.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 22.7,
          windspeed: 16.5,
          winddir: 300,
          pressure: 1018,
          visibility: 10,
          cloudcover: 88,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['EPWA', 'EPMO'],
          source: 'obs',
        },
        {
          datetime: '06:00:00',
          datetimeEpoch: 1663732800,
          temp: 10,
          feelslike: 7.7,
          humidity: 93.19,
          dew: 8.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 22,
          windspeed: 16.5,
          winddir: 310,
          pressure: 1018,
          visibility: 10,
          cloudcover: 88,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['EPWA', 'EPMO'],
          source: 'obs',
        },
        {
          datetime: '07:00:00',
          datetimeEpoch: 1663736400,
          temp: 10,
          feelslike: 7.7,
          humidity: 93.19,
          dew: 8.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 23.4,
          windspeed: 16.4,
          winddir: 300,
          pressure: 1018,
          visibility: 10,
          cloudcover: 88,
          solarradiation: 15,
          solarenergy: 0.1,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['EPWA', 'E1334', 'EPMO'],
          source: 'obs',
        },
        {
          datetime: '08:00:00',
          datetimeEpoch: 1663740000,
          temp: 10.2,
          feelslike: 10.2,
          humidity: 91.02,
          dew: 8.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 31.3,
          windspeed: 13,
          winddir: 334.6,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 93.8,
          solarradiation: 105,
          solarenergy: 0.4,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '09:00:00',
          datetimeEpoch: 1663743600,
          temp: 10.9,
          feelslike: 10.9,
          humidity: 86.29,
          dew: 8.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 29.2,
          windspeed: 12.6,
          winddir: 335.4,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 81.7,
          solarradiation: 211,
          solarenergy: 0.8,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '10:00:00',
          datetimeEpoch: 1663747200,
          temp: 11.8,
          feelslike: 11.8,
          humidity: 80.75,
          dew: 8.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 29.2,
          windspeed: 11.9,
          winddir: 331.8,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 76.1,
          solarradiation: 346,
          solarenergy: 1.2,
          uvindex: 3,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '11:00:00',
          datetimeEpoch: 1663750800,
          temp: 12.8,
          feelslike: 12.8,
          humidity: 73.59,
          dew: 8.2,
          precip: 0,
          precipprob: 19,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 30.6,
          windspeed: 13,
          winddir: 327.3,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 75.8,
          solarradiation: 490,
          solarenergy: 1.8,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '12:00:00',
          datetimeEpoch: 1663754400,
          temp: 13.7,
          feelslike: 13.7,
          humidity: 67.07,
          dew: 7.7,
          precip: 0,
          precipprob: 19,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 31,
          windspeed: 12.6,
          winddir: 332.1,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 85.3,
          solarradiation: 549,
          solarenergy: 2,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '13:00:00',
          datetimeEpoch: 1663758000,
          temp: 14.6,
          feelslike: 14.6,
          humidity: 57.88,
          dew: 6.4,
          precip: 0,
          precipprob: 19,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 32,
          windspeed: 13.7,
          winddir: 338,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 91.4,
          solarradiation: 489,
          solarenergy: 1.8,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '14:00:00',
          datetimeEpoch: 1663761600,
          temp: 14.7,
          feelslike: 14.7,
          humidity: 59.11,
          dew: 6.8,
          precip: 0,
          precipprob: 19,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 34.2,
          windspeed: 14.4,
          winddir: 320,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 87.3,
          solarradiation: 531,
          solarenergy: 1.9,
          uvindex: 5,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '15:00:00',
          datetimeEpoch: 1663765200,
          temp: 13.8,
          feelslike: 13.8,
          humidity: 73.77,
          dew: 9.2,
          precip: 0.6,
          precipprob: 33.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 35.3,
          windspeed: 15.1,
          winddir: 308.2,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 412,
          solarenergy: 1.5,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '16:00:00',
          datetimeEpoch: 1663768800,
          temp: 13,
          feelslike: 13,
          humidity: 79.83,
          dew: 9.6,
          precip: 0.9,
          precipprob: 33.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 35.6,
          windspeed: 14.4,
          winddir: 310.9,
          pressure: 1020,
          visibility: 22.6,
          cloudcover: 97.3,
          solarradiation: 107,
          solarenergy: 0.4,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '17:00:00',
          datetimeEpoch: 1663772400,
          temp: 13,
          feelslike: 13,
          humidity: 78.77,
          dew: 9.4,
          precip: 0,
          precipprob: 33.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 33.5,
          windspeed: 14,
          winddir: 317.7,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 163,
          solarenergy: 0.6,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '18:00:00',
          datetimeEpoch: 1663776000,
          temp: 12.7,
          feelslike: 12.7,
          humidity: 79.25,
          dew: 9.2,
          precip: 0,
          precipprob: 33.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 32.4,
          windspeed: 12.2,
          winddir: 313.6,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 94,
          solarenergy: 0.3,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '19:00:00',
          datetimeEpoch: 1663779600,
          temp: 12,
          feelslike: 12,
          humidity: 81.32,
          dew: 8.9,
          precip: 0,
          precipprob: 33.3,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 27.7,
          windspeed: 10.8,
          winddir: 315.5,
          pressure: 1021,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 5,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '20:00:00',
          datetimeEpoch: 1663783200,
          temp: 11.1,
          feelslike: 11.1,
          humidity: 86.89,
          dew: 9,
          precip: 0,
          precipprob: 33.3,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 23.8,
          windspeed: 9.4,
          winddir: 317.5,
          pressure: 1021,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '21:00:00',
          datetimeEpoch: 1663786800,
          temp: 10.5,
          feelslike: 10.5,
          humidity: 88.62,
          dew: 8.7,
          precip: 0,
          precipprob: 19,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 20.5,
          windspeed: 8.6,
          winddir: 326.3,
          pressure: 1022,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '22:00:00',
          datetimeEpoch: 1663790400,
          temp: 10,
          feelslike: 8.9,
          humidity: 89.18,
          dew: 8.3,
          precip: 0,
          precipprob: 19,
          snow: 0,
          snowdepth: 0,
          preciptype: ['rain'],
          windgust: 18.7,
          windspeed: 8.3,
          winddir: 330.3,
          pressure: 1022,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '23:00:00',
          datetimeEpoch: 1663794000,
          temp: 9.5,
          feelslike: 8.4,
          humidity: 90.97,
          dew: 8.1,
          precip: 0,
          precipprob: 19,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 18,
          windspeed: 7.9,
          winddir: 332.7,
          pressure: 1021,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
      ],
    },
  ],
  stations: {
    E5546: {
      distance: 5690,
      latitude: 52.276,
      longitude: 20.958,
      useCount: 0,
      id: 'E5546',
      name: 'EW5546 Warsaw PL',
      quality: 0,
      contribution: 0,
    },
    E1334: {
      distance: 18083,
      latitude: 52.307,
      longitude: 20.772,
      useCount: 0,
      id: 'E1334',
      name: 'EW1334 Truskaw PL',
      quality: 0,
      contribution: 0,
    },
    EPWA: {
      distance: 7805,
      latitude: 52.17,
      longitude: 20.97,
      useCount: 0,
      id: 'EPWA',
      name: 'EPWA',
      quality: 50,
      contribution: 0,
    },
    EPMO: {
      distance: 34211,
      latitude: 52.45,
      longitude: 20.65,
      useCount: 0,
      id: 'EPMO',
      name: 'EPMO',
      quality: 50,
      contribution: 0,
    },
  },
  currentConditions: {
    datetime: '11:30:20',
    datetimeEpoch: 1663752620,
    temp: 12.5,
    feelslike: 12.5,
    humidity: 78.4,
    dew: 8.8,
    precip: 0,
    precipprob: null,
    snow: 0,
    snowdepth: 0,
    preciptype: null,
    windgust: null,
    windspeed: 14.8,
    winddir: 300,
    pressure: 1019,
    visibility: 10,
    cloudcover: 88,
    solarradiation: 490,
    solarenergy: 1.8,
    uvindex: 5,
    conditions: 'Partially cloudy',
    icon: 'partly-cloudy-day',
    stations: ['E5546', 'EPWA', 'EPMO'],
    sunrise: '06:19:56',
    sunriseEpoch: 1663733996,
    sunset: '18:37:16',
    sunsetEpoch: 1663778236,
    moonphase: 0.91,
  },
}
